# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet another silly blog
email: vincent.latrouite@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Yet another silly blog trying to explain stuff about programming,
    machine learning and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: vincentl111
github_username:  bloody76

# Build settings
markdown: kramdown
